Repository VB10/flutter-ready-to-use-widgets, pull requests merged in 2022-04, with the labels that each got.

#4 custom dropdown widget
  README.md
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/atomic/dropdown/custom_dropdownd.dart
  lib/atomic/dropdown/example_custom_dropdown.dart
  lib/main.dart
Labels: enhancement

#5 Custom widgets created.
  README.md
  github/images/alert_dialog/custom_alert.png
  github/images/button/custom_button.png
  lib/atomic/alert_dialog/custom_alert_dialog.dart
  lib/atomic/button/custom_elevated_button.dart
  lib/main.dart
Labels: enhancement, help wanted, good first issue

#8 Create BaseChart from .csv file
  README.md
  ios/Podfile.lock
  lib/feature/chart/Readme.md
  lib/feature/chart/base_chart.dart
  lib/feature/chart/base_chart_model.dart
  lib/feature/chart/example/ChartCSV.csv
  lib/feature/chart/example/chart_model.dart
  lib/feature/chart/example/example_chart_view.dart
  lib/feature/chart/file_manager.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#6 Network Dependent Widget
  README.md
  lib/feature/network_connection/cubit/network_cubit.dart
  lib/feature/network_connection/cubit/network_state.dart
  lib/feature/network_connection/network_dependent_widget_example.dart
  lib/feature/network_connection/view/network_dependent_widget.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, documentation, enhancement
