Repository VB10/flutter-ready-to-use-widgets, pull requests merged in 2022-05, with the labels that each got.

#9 Dynamic cool toolbar
  README.md
  github/gifs/toolbar/dynamic_cool_tool_bar.gif
  lib/feature/dropdown/dynamic_cool_tool_bar/constants/constants.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/constants/page_border_radius.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/constants/page_padding.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/example/dynamic_cool_tool_bar.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/model/items.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/model/toolbar_item_data.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/widgets/drag_box.dart
  lib/feature/dropdown/dynamic_cool_tool_bar/widgets/toolbar_item.dart
Labels: enhancement, help wanted

#10 AnimatedScaleWrapper
  README.md
  github/gifs/container/animated_scale_wrapper.gif
  lib/atomic/container/animated_scale_wrapper.dart
Labels: documentation

#14 WidgetSlider Added.
  README.md
  lib/feature/widget_slider/Readme.md
  lib/feature/widget_slider/example/slider_example.dart
  lib/feature/widget_slider/widget_slider.dart
Labels: enhancement

#16 Custom Text Field
  README.md
  github/images/custom_text_field/custom_text_field.PNG
  lib/atomic/text_field/custom_text_field.dart
Labels: enhancement

#17 Generic group checkbox added.
  README.md
  github/gifs/group_checkbox/group_checkbox.gif
  github/images/group_checkbox/flutter_group_checkbox_properties.png
  lib/atomic/group_checkbox/example/group_checkbox_example_view.dart
  lib/atomic/group_checkbox/model/abstract_checkbox_item.dart
  lib/atomic/group_checkbox/model/city_model.dart
  lib/atomic/group_checkbox/widget/group_checkbox_builder.dart
Labels: enhancement

#18 AnimatedCrossText
  github/gifs/text/animated_cross_text.gif
  lib/atomic/text/animated_cross_text.dart
  lib/main.dart
  pubspec.lock
Labels: enhancement

#19 Loading Circular Progress
  README.md
  github/images/circular_progress/loading_circular.gif
  ios/Podfile.lock
  lib/atomic/circular_progress/loading_circular_progress.dart
  lib/main.dart
Labels: enhancement

#21 "GlowImage" atomic widget added
  README.md
  github/gifs/image/glow_image.gif
  lib/atomic/glow_image/example_glow_image.dart
  lib/atomic/glow_image/glow_image.dart
  lib/atomic/glow_image/glow_image_clip.dart
  lib/main.dart
  pubspec.lock
Labels: enhancement
